languages:
  JavaScript: true

engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
  fixme:
    enabled: true
  eslint:
    enabled: true
    config:
      config: .eslintrc.js

ratings:
   paths:
   - "**/*.js"

exclude_paths:
- "docs/**/*"
- "dist/**/*"
- "flow-typed/**/*"
- "node_modules/**/*"
- ".vscode/**/*"
- "*"
- ".*"
