language: node_js

node_js:
  - stable

cache: yarn

script:
  - node_modules/.bin/travis-github-status lint flow jest snyk codeclimate # git.repos.createSatus(error count 4 tool)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5c214c2a052a937c9922
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
