language: node_js

node_js:
  - stable

cache: yarn

script:
  - npm run lint
  - ./node_modules/.bin/flow
  - ./node_modules/.bin/jest --coverage
  - ./node_modules/eslint-changes/index.js

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
